runtime: nodejs20
env: standard
instance_class: F1

entrypoint: node server.mjs

env_variables:
  NODE_ENV: "production"
  REACT_APP_CAPTCHA_S: "your-secret-key"

handlers:
  - url: /verify-recaptcha
    script: auto

  - url: /
    static_files: build/index.html
    upload: build/index.html

  - url: /(.*)
    static_files: build/\1
    upload: build/(.*)

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5
